### ISSUE TITLE
Feature: Meta Robots

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya-module-cms#100]
I think it is currently not possible to change meta robots by page, which I think should be possible, as sometimes you'd like to change how search engines crawl/index a site.

E.g. in the LUYA kickstarter it's currently hardcoded
`<meta name="robots" content="index, follow" />`

This could be changed acccording to the other meta fields, so that with another field for CMS pages it would be set individually.
(E.g. in main layout (for kickstarter) instead above it would then be
`$this->registerMetaTag(['name' => 'robots', 'content' => 'index, follow'], 'metaRobots');`)

**Comment by nadar** [comment]
Use a cms page property to define those informations, not sure its relevant and understandable for an "out of the box" implementation. => https://luya.io/guide/app-cmsproperties
