### ISSUE TITLE
Feature Requests : about block fields

### ISSUE THREAD

**Issue by trk** [luyadev/luya-module-cms#102]
- A description area below input field :

![ekran resmi 2018-06-20 20 10 56](https://user-images.githubusercontent.com/455983/41673605-1499fcf8-74c6-11e8-9d3b-776cc90e8fb7.png)

- Disable / Show if support. Example : if field `A` value `=1` show field `B` or if field `A` value `=1|2|3` show field `B`) show | disalble field.

![2018-06-20 20 11 52](https://user-images.githubusercontent.com/455983/41673682-4c7e67d0-74c6-11e8-9e4f-b13eebcf65b8.gif)

- Grouping fields like here :

![ekran resmi 2018-06-20 20 14 08](https://user-images.githubusercontent.com/455983/41673752-8af192e4-74c6-11e8-9397-7b0c78841cbf.png)

- More tabs support with custom tab title like here :

![ekran resmi 2018-06-20 20 15 04](https://user-images.githubusercontent.com/455983/41673787-ade3b304-74c6-11e8-8d4d-07263677b0c3.png)

- Default value for fields (if field has no value set default value)

**Comment by trk** [comment]
- Field column width like :
![ekran resmi 2018-06-21 15 37 18](https://user-images.githubusercontent.com/455983/41719600-2e2d892a-7569-11e8-9fac-65492c8c96d6.png)

**Comment by nadar** [comment]
@trk regarding info/hints/description, see: 

```php
public function getFieldHelp()
{
    return [
        'content' => 'An explain example of what this var does and where it is displayed.',
    ];
}
```

**Comment by nadar** [comment]
is done by getFieldHelp() if more infos or changes are requested, please re open the issue with more informations.
