### ISSUE TITLE
Remove frontend toolbar logo link ?

### ISSUE THREAD

**Issue by trk** [luyadev/luya-module-cms#103]
When i want to open toolbar, wrongly clicking link and opening https://luya.io/.

Is it possible to remove link from toolbar ?

**Comment by nadar** [comment]
@luyadev/core where could we put the logo in the toolbar?

**Comment by trk** [comment]
You can keep logo on toolbar.

**Comment by nadar** [comment]
@trk i would like to keep the link. But we could move the logo the the left side of the toolbar. @TheMaaarc @dev7ch should not be that complicated?

**Comment by TheMaaarc** [comment]
Updated the toolbar, switched the visibility indicator (eye) with the logos position. Is it ok like that or do you want the eye on the left side @nadar?

**Comment by nadar** [comment]
Thanks for taking care of this @TheMaaarc. Personally i would put it to the left side or do you think its better this way?

**Comment by TheMaaarc** [comment]
I mainly did it to separate clickable elements from static elements that indicate a status – I think that distinction makes sense.

**Comment by nadar** [comment]
All right, lets keep it like this then and you can close the issue.

**Comment by TheMaaarc** [comment]
👍
