### ISSUE TITLE
Layout column title tag always in html

### ISSUE THREAD

**Issue by trk** [luyadev/luya-module-cms#111]
I want use layout columns without `title` (I can).
If i don't set a `column title` title tag still appear in html and title tag pushing content.

![ekran resmi 2018-07-02 20 59 30](https://user-images.githubusercontent.com/455983/42179013-1ff45d5e-7e3b-11e8-8134-185631a5e126.png)

**Comment by nadar** [comment]
Hi @trk 

So this is a feature or a bug? Sorry i don't understand the problem or the feature. Its an existing block? Could you provide more informations? thanks

**Comment by trk** [comment]
If we don't have content for title, we don't need title html tag there. Empty tags pushing content.

On my side i don't want to use title for layout columns, and if don't use title for columns, don't want to display empty title html tags.

**Comment by nadar** [comment]
Ok i understand.

**Comment by nadar** [comment]
@TheMaaarc i think we could just add ng-show="title" in order to fix this - or does this have a problem with margin/padding?

**Comment by TheMaaarc** [comment]
Will test it and propose a solutions asap

**Comment by nadar** [comment]
Any news on this @TheMaaarc ?
