### ISSUE TITLE
Translations not working for block groups

### ISSUE THREAD

**Issue by trk** [luyadev/luya-module-cms#112]
i can see translation key on block label section.

<img width="447" alt="ekran resmi 2018-07-03 03 47 27" src="https://user-images.githubusercontent.com/455983/42192804-d44a24e0-7e73-11e8-8b82-4c243029e3b2.png">

**Comment by nadar** [comment]
Block group translations should work, as we use them too:

https://github.com/luyadev/luya-module-cms/blob/master/src/frontend/blockgroups/LayoutGroup.php#L23 Maybe your module registration process. Please add more infos on how you have registered the module, i will close the issue until then.
