### ISSUE TITLE
CMS page type: module controller/action \w parameter binding

### ISSUE THREAD

**Issue by Webkadabra** [luyadev/luya-module-cms#113]
I'd like to have a feature to be able to define more option for "Module" page type. 
Basically, I'm looking for a way to create a CMS page with customer route (e.g. /buy-iphone/) and configure it to "shop/good/view/id/25" route. I have made this is my CMS module (not LUYA), and wondering if it's available in LUYA?

**Comment by Webkadabra** [comment]
Also, as a smaller feature - could we define a controller different then "Default" for CMS page of "module" type ?

**Comment by Webkadabra** [comment]
I found out that you can have custom CMS page and use more module configuration via adding module widget

**Comment by nadar** [comment]
Hi @Webkadabra with the module block you can define the controller, action and also params. The module page is really thought to provide full controller for a given module, if its about the controller you can also change the defaultRoute for a module.
