### ISSUE TITLE
Enhancement: allow  to disable route inheritance

### ISSUE THREAD

**Issue by Webkadabra** [luyadev/luya-module-cms#118]
I'd like to be able to disable route inheritance for specific pages.
For example, I have pages:

1. Supplements (landing page, showing collection of products)
`url`: example.com/supplements

2. Single product landing page, that I want to be under `Supplements` **navigation**,
but have it's own url like `example.com/super-healthy-product`.

Do you think adding another option to a page like `Don't inherit parent route` is something that can be considered? Or should I think of another ways of structuring my content?

**Comment by nadar** [comment]
I think the hierarchical representation of the menu and the navigation should be the same. Why not make a new container like "landingpages" and add "super-healthy-product" as page in this container? This is maybe the best way to keep your pages organized and structured.

**Comment by nadar** [comment]
instead of chaning the page mechnism, maybe you should trick the breadcrumb widget for this scenario.

**Comment by Webkadabra** [comment]
I will implement how I see it in my fork and let you decide if it's worth a pull request

**Comment by Webkadabra** [comment]
Yeah, t's a *little* bit more complicated then I anticipated. I got the UI part though, haha. I mean, I can manage to make the thing work (skip alias prepending for `is_singleton_router`), but then pages that have root would not be displayed under their root menu. I basically wanted to change url part only, not menu behavior. 

I will push my code with UI updates to a branch on my fork, just in case.

**Comment by nadar** [comment]
So you agree we can close the issue as you have made a solution for yourself? I don't this is something we should adopt, we have a very large range of peopling using the cms - they won't understand what this button is all about. The cms admin is mainly thought not for developers, its for editors.

Or do you have another suggestion how to implement such a feature?

**Comment by Webkadabra** [comment]
@nadar yep, it's probably overkill
