### ISSUE TITLE
Texteditor Formatting/Checks (Feature "Editor Switch")

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya-module-cms#119]
Currently when using the text editor it sometimes misses to make a paragraph and uses a `<br/>` instead.
If this happens, it's hard to remove them and change them to a paragraph (I had to create the block again, copy content without formatting and format by hand). Moreover I get an empty paragraph after each texteditor area.

I think it would make sense to have an "Editor Switch", somehow comparable to the switch in e. g. WordPress, so that the html code can be reviewed and adjusted.

**Comment by nadar** [comment]
so you are talking about zaa-wysiwyg?

**Comment by JohnnyMcWeed** [comment]
yes, it is zaa-wysiwyg.

**Comment by JohnnyMcWeed** [comment]
I'll add `source-mode-allowed` to ng-wig and change the scss for the icon and then make a PR.
Should then work I think. Not very beautyful, but at least we can go for it... (https://github.com/stevermeister/ngWig#edit-source-option-plunker)

**Comment by nadar** [comment]
Perfect! yes please send a pr. i am going to move the issue to admin module so you can refer to the new issue. thanks!
