### ISSUE TITLE
Make sitemap for selecting internal links collapsible

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-cms#124]
We received this request from two customers within the same week: When selecting the destination of an internal link, the sitemap to do so is open and not collapsible:

![sitemap 1](https://user-images.githubusercontent.com/3786245/43452802-a939fcde-94b8-11e8-85b1-cd7f936726a5.png)

This is confusing and user-unfriendly on bigger websites where the sitemap can get quite long:

![sitemap 2](https://user-images.githubusercontent.com/3786245/43452895-dc6d11ae-94b8-11e8-88fa-665ec53d5a05.png)

The sitemap should initially be collapsed so that it is easier to navigate to the target node. It could look similar to the website's site tree, with the "target circles" next to the page name:

![sitemap 3](https://user-images.githubusercontent.com/3786245/43453088-63a19ffa-94b9-11e8-9a1c-555cfb901553.png)

**Comment by nadar** [comment]
https://github.com/luyadev/luya-module-cms/issues/20 - we where already talking about improve the link directives, so i am going to close this, so we can summarize all improvements and do them all together.
