### ISSUE TITLE
Drag & Drop in Chrome/Safari

### ISSUE THREAD

**Issue by boehsermoe** [luyadev/luya-module-cms#139]
With CMS Version 1.0.6.0 and Admin Version 1.2.2.0 the Drag & Drop does not working. In my other Project with 1.0.5.0 and 1.2.1.0 it is working. Can someone confirm this problem with
Chrome Version 68/69 and Safari 12? With Firefox 62 it works fine.
Tested under mac os 10.13.6.

**Comment by nadar** [comment]
Latest cms and admin dev-master on my Ubuntu 18.04 with Chromium Version 69.0.3497.100 (Official Build) (64-bit) it works.

**Comment by nadar** [comment]
@boehsermoe and if you install latest dev-master?

**Comment by boehsermoe** [comment]
I figure out that the problem is only when trying drag & drop with the black toolbar of the block. With the older CMS/Admin Version it works with the black toolbar but not with newer version, also on mac and ubuntu.

**Comment by nadar** [comment]
Maybe this is related to: https://github.com/luyadev/luya-module-cms/issues/14

Not sure this an expected behavior of this change or not. But i agree, it would make sense if its also possible to start dragging from the toolbar.

**Comment by nadar** [comment]
@TheMaaarc maybe we should fix this soon as it also occurs on latest chrome versions.

**Comment by TheMaaarc** [comment]
Chrome/Safari seems to have an issue when the element that starts the drag, in this case `block__toolbar`,  gets hidden (`display: none` *or* `visibility: hidden`) while still dragging.

I `fixed` this now by just not hiding it 🤷‍♂️
