### ISSUE TITLE
created and specified error 404 page don't displayed when url was typed wrong

### ISSUE THREAD

**Issue by NePeter** [luyadev/luya-module-cms#152]
Site is single language.
1. I create my page with error 404 message:
![1](https://user-images.githubusercontent.com/11742167/39998402-a8052d6e-578e-11e8-8573-eeb56b535fde.png)
2. I specify this page and do Save:
![2](https://user-images.githubusercontent.com/11742167/39998585-303f8eb8-578f-11e8-9bfb-870352630c23.png)
3. After  typing wrong url for example my_site_name/privet on the screen displayed standard 404 page, but not my page.
![3](https://user-images.githubusercontent.com/11742167/39998720-a994bc34-578f-11e8-89e8-7a234e34a63d.png)

**Comment by nadar** [comment]
@NePeter Have you disabled YII_DEBUG? cause this will only work when YII_DEBUG is not true.

**Comment by NePeter** [comment]
Thank you! After I defined YII_DEBUG = false everything is OK!
But there is small bug: if i add two characters to url for example https://peter.net.ru/fg (it's a real address of my test site) i have message 'An internal server error occurred.'

**Comment by nadar** [comment]
Please create another issue for this problem, but it seems you don't have a multi lingual website and should therefore.

a. disable composition (hidden = true)
b. and change the composition pattern, as long as you need cms paths with 2 chars (which is interpreted as language short code) https://github.com/luyadev/luya/blob/master/core/web/Composition.php#L78-L78
