### ISSUE TITLE
after deleting template redirect to not exist update page

### ISSUE THREAD

**Issue by igorveremsky** [luyadev/luya-module-cms#153]
i delete page 
![screenshot_154](https://user-images.githubusercontent.com/13087365/36797161-f61aed8c-1caf-11e8-9939-ccb21f56634e.png)

and than redirect to page with white space because the url is update action for page that i deleted before:
![screenshot_155](https://user-images.githubusercontent.com/13087365/36797225-18994d54-1cb0-11e8-851c-536ad9fb8620.png)

**Comment by nadar** [comment]
I don't think this is a problem, The page is deleted and hidden correctly, after taking the next action the url will change. If i did not recognized the problem correctly, please leave a comment.

**Comment by igorveremsky** [comment]
yes, page deleted and hidden correctly but why by default after deleting cms redirect user to edit page that was deleted before? Thats the question and the main goal of this issue. thanks.

**Comment by nadar** [comment]
@igorveremsky its not redirecting, i just keeps the old url from the previous deleted page, but its not a problem.

**Comment by igorveremsky** [comment]
@nadar ok, unfortunately i don`t know why you ned to do this, for example show page with all pages after deleting will be more consistent. Whatever, maybe its just my thinking, vision.

**Comment by nadar** [comment]
Maybe a dialog which says "the page has been deleted" would be good  (there is a notification thought) - a page with all pages is not needed, you can see the menu tree to the left.

**Comment by igorveremsky** [comment]
Sounds good

пн, 4 бер. 2019 о 12:19 Basil <notifications@github.com> пише:
