### ISSUE TITLE
Internal page redirection to first sub page

### ISSUE THREAD

**Issue by martinpetrasch** [luyadev/luya-module-cms#157]
If someone is creating a blog or a newsfeed, it would be nice to be able to link a main nav item to the first sub page (=last created page).

It could also be practical to discuss other "logic based" redirection rules (i.e. newest sub page or oldest etc.).

**Comment by nadar** [comment]
You can do this already by using orderBy (https://luya.io/api/luya-cms-menu-Query) in your menu query?

**Comment by martinpetrasch** [comment]
I know, but I want the option inside the CMS redirection page options without adding a manual exception with the menu query builder.

**Comment by nadar** [comment]
How should this look like? How would you explain such a "link option" to end users? Please make a concrect implementation example (its a type? its part of link directive? ... ideas). Make an example for the Look and Feel for such an option.

**Comment by rolandschaub** [comment]
This is how TYPO3 does it:

<img width="358" alt="verweis-modus typo3" src="https://user-images.githubusercontent.com/3786245/48420903-b8025180-e75b-11e8-8026-0057a32c9bf3.png">

So they have four options for redirections to choose from:

1. Selected page (as we have it in LUYA)
2. First sub page of current page
3. Random sub page of current page
4. Parent page of selected/current page

Martin's suggestion would be an additional option "Newest sub page of current page" (it's not the same as "First sub page of current page", which refers to the first sub page in the order defined in the site tree).

I don't think we need option 3, but the other options would be useful.

**Comment by nadar** [comment]
But how should this implement in LUYA - its a directive? a new type? it extends the current redirect directive? Where do i use it?

**Comment by rolandschaub** [comment]
It extends the current link directive. Something like this:

![link-directive](https://user-images.githubusercontent.com/3786245/48422548-31e80a00-e75f-11e8-93c0-60d89ac66e33.gif)

**Comment by nadar** [comment]
This is what internal redirects look like: 

![image](https://user-images.githubusercontent.com/3417221/48422850-c6eb0300-e75f-11e8-847c-8822e1e66a31.png)

I understand your idea, but i assume this is very hard to understand for "casual admin users".

**Comment by rolandschaub** [comment]
I don't think so, it's quite evident. The selection menu could be situated below "Choose the internal page…". If "Selected page" is active, the navigation containers are visible. If the other options are active, they are hidden.

**Comment by nadar** [comment]
Keep in mind we will restructure the internal page directive => https://github.com/luyadev/luya-module-cms/issues/20 Also you should know those are all generic directive components.

We can keep the issue, but maybe you should make a drawing after the refactoring.

**Comment by rolandschaub** [comment]
Okay.

**Comment by nadar** [comment]
We have refactored the tree view, you can now make a new drawing of how this should look like, but i still don't think this is a high prio issue.

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
