### ISSUE TITLE
Feature Request: Page properties for Open Graph, Twitter and meta data and canonical URL

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-cms#159]
Make the following meta information (Open Graph, Twitter, canonical URL) editable as page properties:

```html
<meta property="og:title" content="[ TITLE ]" />
<meta property="og:type" content="article" />
<meta property="og:description" content="[ ARTICLE DESCRIPTION ]" />
<meta property="og:image" content="[ LISTING IMAGE ]" />
<meta property="og:url" content="[ CANONICAL URL OF ITEM ]" />

<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="[ TITLE ]">
<meta name="twitter:description" content="[ ARTICLE DESCRIPTION ]">
<meta name="twitter:image" content="[ LISTING IMAGE ]">
<meta name="twitter:url" content="[ CANONICAL URL OF ITEM ]">

<link rel="canonical" href="[ CANONICAL URL OF ITEM ]">
```

Summary of the page properties required:
- og-title
- og-description
- og-image
- canonical url

If no values are defined, the following default values should be used:
- og-title: page title
- og-description: meta description
- og-image: none
- canonical url: the page url

**Comment by boehsermoe** [comment]
Instead to use no image if none og-image is specified isnt it better to use the a fallback? Maybe a global fallback defined in the cms config or the first image element on the page? Or both?

New page properties require a migration.

**Comment by rolandschaub** [comment]
Regarding og-image: I think it's okay to configure a global fallback. If undefined, the tag should not be output so that Facebook and others can decide themselves what image to choose (if any are included in the page's content). I would not use the first image in the content as default, as FB et al. might make a better guess which image is relevant for the page.

Regarding canonical url: The default value would be the current URL. The website editor (or a module like an online shop) has to explicitly set another URL if the current URL is not the canonical one. I might be wrong, but this makes sense to me.

**Comment by TheMaaarc** [comment]
> The website editor (or a module like an online shop) has to explicitly set another URL if the current URL is not the canonical one. I might be wrong, but this makes sense to me.

@rolandschaub is right. Google recommends using self-referencing canonical tags.
