### ISSUE TITLE
Feature Request: Move blocks up and down

### ISSUE THREAD

**Issue by boehsermoe** [luyadev/luya-module-cms#161]
Sometimes it is hard to move a block from the bottom to the top. Or I want to switch the order of two blocks and if the block is large, its much harder. Maybe it will be easier with a toggle function #149.
But in general I think it would be helpful when I can move a block up and down to the next block (inside of the placeholder area/container).

**Comment by nadar** [comment]
But Cut & Paste would fix this problem to?

**Comment by boehsermoe** [comment]
Maybe partly. With a button to push block down or to end it faster. And it is much more mobile friendly.

**Comment by nadar** [comment]
Maybe it would be faster, but we should not clutter the UI with to much buttons, i am not saying this is not a good idea - maybe the block toggler would be more useful, then the dragging would no be a problem anymore?

**Comment by boehsermoe** [comment]
I agree. We should wait for Cut&Paste and block toggler feature.
