### ISSUE TITLE
Changing page type from "redirect" to "page" doesn't create empty page version

### ISSUE THREAD

**Issue by martinpetrasch** [luyadev/luya-module-cms#17]
### What steps will reproduce the problem?
Change a "redirect" page to "page" type

### What is the expected result?
There should be a first empty version of the page (like when you create a new page with type "page")

### What do you get instead? (A Screenshot can help us a lot!)
An empty page without any versions in it.

**Comment by nadar** [comment]
Sure, good point. thanks for the report
