### ISSUE TITLE
zaa-checkbox initvalue

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-cms#188]
### What steps will reproduce the problem?

Set the `initvalue` of the `zaa-checkbox` plugin to `1`.

Example from the [docs](https://luya.io/guide/app-block-type-checkbox):
`['var' => 'mycheckbox', 'label' => 'Check this!', 'type' => self::TYPE_CHECKBOX, 'initvalue' => 1]`

### What is the expected result?

A checked checkbox when I add a new block.

### What do you get instead? (A Screenshot can help us a lot!)

Unchecked checkbox. 👀 

![screenshot 2019-03-08 at 09 42 49](https://user-images.githubusercontent.com/3450438/54017534-8e47bd00-4186-11e9-883b-38a81d7230ac.png)

**Comment by nadar** [comment]
yes, i think initvalue does not work for checkbox, until now.

**Comment by hbugdoll** [comment]
Is this issue still actual?

Tested with Admin module v4 & CMS module v4:

![luya_checkbox_initvalue](https://user-images.githubusercontent.com/6715827/135229268-a440f760-09e6-4375-b1fd-8e29cc8b3554.png)

**Comment by nadar** [comment]
Thanks for the test! So i think we can close this issue :+1:  thanks
