### ISSUE TITLE
dirname() expect 1 but two given. Sometimes give timeout

### ISSUE THREAD

**Issue by corentinchap** [luyadev/luya-module-cms#189]
### What steps will reproduce the problem?
Install luya-kickstarter-bootstrap4 through composer
Copy config, link to a database
php index.php migrate
php index.php import
php index.php admin/setup

### What do you get instead? (A Screenshot can help us a lot!)

![image](https://user-images.githubusercontent.com/9058675/54081975-34432500-4349-11e9-83d5-d4a73bc13fd5.png)

### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

$ php index.php health
The directory the health commands is applying to: C:\xampp\htdocs\luya-coiffure-booking
public_html/assets: directory exists already
public_html/storage: directory exists already
migrations: directory exists already
vendor: directory exists already
runtime: directory exists already
configs/env.php: file exists.
public_html/index.php: file exists.
O.K.?[0m?[32m
?[0m

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  1.0.0
| PHP Version      |  PHP 5.6.38 
| Platform         | XAMPP
| Operating system | Windows

**Comment by nadar** [comment]
@boehsermoe https://github.com/luyadev/luya-module-cms/blob/1.0/src/base/InternalBaseBlock.php#L642 - intersting

**Comment by boehsermoe** [comment]
The 2nd parameter `$level` is available only in > PHP 7.0 
http://php.net/manual/en/function.dirname.php

**Comment by nadar** [comment]
As lot of CLI envs are still using older PHP version we should keep PHP 5.6 - the unit tests for 5.6 are just failing because of newer php unit version. So yes, i think we should keep 5.6 until its a clear requirement for LUYA
