### ISSUE TITLE
Fix css spacing on cms page

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-cms#194]
Unify spaces between treenav & page and between page languages.

**Comment by nadar** [comment]
@TheMaaarc And maybe remove the usless line between translations?

**Comment by TheMaaarc** [comment]
👍

**Comment by nadar** [comment]
![image](https://user-images.githubusercontent.com/3417221/58185889-2a785f00-7cb4-11e9-89d7-115575785a98.png)

**Comment by TheMaaarc** [comment]
@nadar Okay, should now be 20px in the dashboard and page view.
