### ISSUE TITLE
Two Treeview link chooser on same page

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-cms#20]
Only the "Default container" that you click on should be opened. Not both.

![2018-01-03 09_14_53](https://user-images.githubusercontent.com/3450438/34513128-d78eabf8-f066-11e7-8383-9b6ae630b3b8.gif)

**Comment by nadar** [comment]
We should discuss about a general solution for links, this could also be used within zaa-links and everywhere else where page selection is done (like now, but different layout. Maybe a modal?)

**Comment by nadar** [comment]
This is because its the same directive, opening linke selection in a new modal would fix this problem and then we could maybe improve the link selection in general (with the containers, etc.)

**Comment by TheMaaarc** [comment]
Ahh, okay. Well, maybe a modal would be a good solution. The tree can grow quite big for certain sites.

**Comment by nadar** [comment]
Yes i agree. So that's why i am saying, maybe we should restructure the whole element to fix all the issues. I think its worth to spent some time on this.

**Comment by nadar** [comment]
We should make a list of changes, so we can do them all together (see also #124).
