### ISSUE TITLE
Editing data in multiple page CRUD results in "flickering" when saving data

### ISSUE THREAD

**Issue by martinpetrasch** [luyadev/luya-module-cms#200]
### What steps will reproduce the problem?
1. Open CRUD overview with multiple pages
2. Go to last page and edit last data entry
3. Change a property and press "Save"

### What is the expected result?
Return to CRUD overview on last page.

### What do you get instead? (A Screenshot can help us a lot!)
Returning to CRUD with fast flickering between page 1 and last page, while loading bar is active. After loading bar is finished, you'll end on page 1.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     |  dev-master (admin & cms)

**Comment by nadar** [comment]
duplicated? https://github.com/luyadev/luya-module-admin/issues/317
