### ISSUE TITLE
CMS 404 page is not shown when NotFoundHttpException is thrown

### ISSUE THREAD

**Issue by cebe** [luyadev/luya-module-cms#203]
### What steps will reproduce the problem?

`throw new NotFoundHttpException()` 

### What is the expected result?

I have configured 404 page in CMS so I expect to see it.

### What do you get instead? (A Screenshot can help us a lot!)

![Bildschirmfoto von »2019-06-24 14-36-00«](https://user-images.githubusercontent.com/189796/60019113-6aed4300-968d-11e9-9993-24508acf65a5.png)

which seems to be the Yii2 default error view.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | dev-master
| PHP Version      | 7.1
| Platform         | Apache
| Operating system | Debian GNU/Linux

**Comment by nadar** [comment]
https://github.com/luyadev/luya-module-cms/commit/8b5e4a4b2328706ba93b6ce48f3e99b8ab009046#diff-d046b35c75e995c7a82c4244f7b55687

We should again attach to the error handler event, but not redirect to the error page. We where unable to render the page content within the given error context. 

> @cebe: yes, or run the cms action in the error handler

**Comment by cebe** [comment]
proposed fix in #204
