### ISSUE TITLE
traverse in block context

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-module-cms#206]
An option to find all blocks from the current block:

+ descendants = all children (including sub sub sub ... items) 
+ children
+ same level
+ parent
+ next
+ previous

not sure about syntax.

```php
self::find()->children()->all()
```

analog to menu, file and active record.

What does the block contain?

+ Variables - from db
+ Cfgs - from db
+ extra data - on call request
+ the block object

**Comment by rolandschaub** [comment]
Maybe `self::find()->descendants()->all()`

**Comment by nadar** [comment]
self = Block Object

Maybe it should also be possible to injected the current context to children by DI (?).

Example use case:

Form Block (new ActiveForm)
  Input Block ($form->field($model, 'field_name'). also write back $model informations: $model->addRule()..

**Comment by nadar** [comment]
descendants() = all children
parents() = all parent items
