### ISSUE TITLE
Template: Blocks in placeholder-block not showing on created page

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-cms#21]
If you create a template with a placeholder block with blocks in it these blocks in the placeholder won't show on a page created with this template.

**Template (expected on page that is created based on this template):**  
![image](https://user-images.githubusercontent.com/3450438/34667182-3109620e-f468-11e7-84f1-1d8399b14271.png)

**Actual page:**  
![image](https://user-images.githubusercontent.com/3450438/34667212-57bf8568-f468-11e7-9587-99a63f962ded.png)

**Comment by nadar** [comment]
@TheMaaarc could you please post the block configuration or the whole block class?

**Comment by nadar** [comment]
https://github.com/luyadev/luya-module-cms/blob/master/src/models/NavItem.php#L372-L417 Problem must be here with recursions (parent nav ids)

**Comment by nadar** [comment]
missing prev_id reset: https://github.com/luyadev/luya-module-cms/blob/master/src/models/Nav.php#L611-L616
