### ISSUE TITLE
Page Permissions issue

### ISSUE THREAD

**Issue by ifuratdev** [luyadev/luya-module-cms#216]
### What do you get instead? (A Screenshot can help us a lot!)
It seems page permission is not working,
I have created 2 groups 
the second group doesn't removed access to the address book page as per image below
I have tried to remove addressbook permission from the group permissions and add it also, but still there is no effect by the image below.

![Page PermisIsions issue](https://user-images.githubusercontent.com/18122838/63114953-d3c2ae80-bf9e-11e9-8382-75c6378730ea.png)### LUYA Check ouput (run this script and post the result: [luyacheck.php](https://gist.github.com/nadar/022f890e064c068e75ce6178cd14a09e))

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 
| PHP Version      |
| Platform         | Apache/XAMPP/MAMPP/etc.
| Operating system | Windows/Linux Server/OSX/etc.

**Comment by ifuratdev** [comment]
thanks :)

**Comment by nadar** [comment]
Permission system works in my case - but it shows the navigation item, but you can not click on it. Have you tested this?

**Comment by ifuratdev** [comment]
yes, i've tested it
below is a screen shot from the cms
and the client group permissions

cms screen
![Page Permissions issue2](https://user-images.githubusercontent.com/18122838/63123936-d6c79a00-bfb2-11e9-907d-9d87dd5a6680.png)

client group permissions
![Page Permissions issue3](https://user-images.githubusercontent.com/18122838/63123946-db8c4e00-bfb2-11e9-8b51-6dd5191373ab.png)

**Comment by ifuratdev** [comment]
and the logged in user for the cms a user in the client group only

**Comment by nadar** [comment]
This has nothing to do with frontend - it only affects admin area.

**Comment by ifuratdev** [comment]
thanks for the clarification,  
how the page is added to the admin menu, when removed the permission from the client group for the addressbook and created a page and allowed client group on this page, i cannot see this page anywhere in the admin menu

**Comment by nadar** [comment]
> how the page is added to the admin menu, when removed the permission from the client group for the addressbook and created a page and allowed client group on this page, i cannot see this page anywhere in the admin menu

Sorry i don't understand what you are trying to ask.

**Comment by ifuratdev** [comment]
as you mentioned "Page Permissions" only affects the Admin area, where can I see the link for the Addressbook page in the Admin area.

I have removed Addressbook permission for the "Client Group" as per picture 2 below
But Added permission using "Page Permissions" to "Client Groups" as per picture 3 below

and the result is picture 1 below

Picture 1:
There is no link for Addressbook page in the Admin menu for a user in the "Client Group"
![Page Permissions issue4](https://user-images.githubusercontent.com/18122838/63214254-a735a080-c11e-11e9-9c46-03c4eb4d4d72.png)

Picture 2:
Client Group permissions
![Page Permissions issue3](https://user-images.githubusercontent.com/18122838/63214265-c3394200-c11e-11e9-889d-65af273aff51.png)

Picture 3:
Page permissions
![Page Permissions issue5](https://user-images.githubusercontent.com/18122838/63214269-d0eec780-c11e-11e9-9725-27fa8866d68d.png)

**Comment by nadar** [comment]
The group must have at least pages permission in CMSADMIN in order to see the pages.
