### ISSUE TITLE
Admin UI touching not working in pages

### ISSUE THREAD

**Issue by testt23** [luyadev/luya-module-cms#217]
Hi everybody,
An important problem that hinders the system when using a cellphone.  When you add a new page you can't add items with the touchpad on her phone, that means you can't post a new page successfully, the problem is terrible.

**Comment by testt23** [comment]
This; https://stackoverflow.com/questions/5186441/javascript-drag-and-drop-for-touch-devices

**Comment by nadar** [comment]
we don't use jquery

**Comment by nadar** [comment]
This is the drag and drop library i have created for luya => https://github.com/luyadev/luya-module-admin/blob/master/src/resources/js/dnd.js if you like to help.
