### ISSUE TITLE
Bug in handleBlockDefintionInDirectories() method of BlockImporter class

### ISSUE THREAD

**Issue by Antikon** [luyadev/luya-module-cms#230]
### What steps will reproduce the problem?
Run unit tests on Windows. BlockImporterTest will fail.

```
1) cmstests\src\admin\importers\BlockImporterTest::testBasicBlockImporter
Failed asserting that Array &0 (
    'luya\cms\admin\importers\BlockImporter' => Array &1 (
        0 => 'Insert new block group block_group_dev_elements.'
        1 => 'block \luya\cms\frontend\blocks\HtmlBlock: Added to database'
        2 => 'Insert new block group block_group_dev_elements.'
        3 => 'block \luya\cms\frontend\blocks\ModuleBlock: Added to database'
-->  4 => 'Unable to find 'D:\htdocs\rjuse\vendor\luyadev\luya-module-cms/tests/data/blocks/import' in any of those paths 'D:\htdocs\rjuse\vendor\luyadev\luya-module-cms,''
        5 => 'Block importer finished with 2 blocks.'
    )
) is identical to Array &0 (
    'luya\cms\admin\importers\BlockImporter' => Array &1 (
        0 => 'Insert new block group block_group_dev_elements.'
        1 => 'block \luya\cms\frontend\blocks\HtmlBlock: Added to database'
        2 => 'Insert new block group block_group_dev_elements.'
        3 => 'block \luya\cms\frontend\blocks\ModuleBlock: Added to database'
        4 => 'Insert new block group block_group_basic_elements.'
        5 => 'block \cmstests\data\blocks\import\TestBlock: Added to database'
        6 => 'Block importer finished with 3 blocks.'
    )
).
```

### The Reason
The problem seems to be in a `handleBlockDefintionInDirectories()` method.
Line 122 `$path = rtrim($directoryPath, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . ltrim($blockDefinition, DIRECTORY_SEPARATOR);` should trim slashes or backslashes from $blockDefinition and concatenate it with $directoryPath. But on Windows the absolute path starts from drive letter, so the $path becomes `\D:\htdocs\rjuse\vendor\luyadev\luya-module-cms/tests/data/blocks/import` (with an unnecessary backslash in front).

### LUYA Check ouput
```
1: [in_array('mod_rewrite', apache_get_modules())] true
2: [ini_get('short_open_tag')] '1'
3: [ini_get('error_reporting')] '22527'
4: [phpversion()] '7.1.26'
5: [php_ini_loaded_file()] 'C:\\Program Files\\PHP\\php.ini'
6: [php_sapi_name()] 'apache2handler'
7: [isset($_SERVER['SERVER_SOFTWARE']) ? $_SERVER['SERVER_SOFTWARE'] : unknown] 'Apache/2.4.18 (Win64) PHP/7.1.26'
```

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA CMS Version     | 2.1.1
| PHP Version      | 7.1.26
| Platform         | Apache
| Operating system | Windows

**Comment by nadar** [comment]
I see.

What would be the value of `$blockDefinition` and `$directoryPath` in your situation?

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
