### ISSUE TITLE
Url parameters encoding/decoding for module blocks.

### ISSUE THREAD

**Issue by jettero777** [luyadev/luya-module-cms#241]
Hello,

Let's say we have complex page layout (like portal) and many modules can be on the same page (module blocks).

And for example we have news module. List/single output of the module in the main column while page's sidebar contains other modules, so we have to use module blocks for such layout and so the news module should have only one action. Because we can't change action for a block module depending on request, right?
So for list and single outputs same action is used, this action decides what to output based on url parameters.

Now I want to integrate url parameters for such news block into pretty url. I can't use route to the module, as in doc examples, because many modules should be displayed on same page, so I need to integrate parameters into CMS's page routes.
I wrote such rule:
```
public $urlRules = [
    '<path:[a-zA-Z0-9\-\/]+>/news-<newsId:\d+>' => 'cms/default/index',
];
```
I used 'path' parameter to pass pages to usual CMS route.

And for url creation I use 
```
Url::toRoute([
    '/cms/default/index',
    'path' => \Yii::$app->menu->current->alias,
    'newsId' => $id
]);
```
This works fine and creates url like `http://host/some-page/news-123`
But there is a drawback, it works well only for top level pages, if I use subpage it will be encoded to `http://host/some-page%2Fsome-subpage/news-123` because path is treated as param and being urlencoded.

I can resolve it using another url encoding:
```
Url::toRoute(['/' . \Yii::$app->menu->current->alias . "/news-{$id}"]);
```
and this works for subpages too, but here is drawback that the url rule is being defined in 2 places and if I change module's url rules in the future I will have to change url encodings in controller too. So it is not good design.

So maybe I miss something and there is another way to include url params for module blocks in pretty url without mentioned drawbacks?

**Comment by nadar** [comment]
https://github.com/luyadev/luya-module-cms/blob/master/src/frontend/components/CatchAllUrlRule.php

Maybe this helps? `encodeParams`

**Comment by nadar** [comment]
I am going to close this issue because:

- Its a question (Please post questions at [forum.luya.io](https://forum.luya.io))
- Missing information's
- No more activity
- No one picked up the task (no Pull Request received)

If you think this is still important or there are more/new informations. **Please reopen the issue and let us know**.

If this is a problem or a feature you like to discuss, join our forum: [forum.luya.io](https://forum.luya.io). We try to keep our issue tracker as clean as possible in order to focus on active issues.
