### ISSUE TITLE
Feature Request: Multi-Site Capability

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-cms#252]
There are situations where one CMS installation should be used to manage and run multiple websites with individual domain names. As an example, a company with several products wants to publish a microsite for each product with the product's name as a domain name. The same editors would maintain the website and some of the assets would be shared (like the company's logo). In this case, it would make sense to only have one LUYA CMS installation that runs all websites.

Things to consider:
+ Use navigation containers to differentiate between websites (e.g. in multi-site environments, for each navigation container a website has to be assigned)?
+ URLs may only be exclusive per website, not per CMS installation as each website could have a /home or /contact URL.
+ It should be possible to copy pages and blocks between websites.
+ Websites should be able to share or use their own templates.
+ Websites should still be able to have multiple language versions.
+ Storage URLs should be shared between websites as they can use the same files.

There are probably more issues to consider.

**Comment by boehsermoe** [comment]
Also for each website should have a other active theme
