### ISSUE TITLE
Slug field missing

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya-module-cms#275]
### What steps will reproduce the problem?
Open page settings to change the slug

### What is the expected result?
Slug field is there

### What do you get instead? (A Screenshot can help us a lot!)
No slug field 
[Screenshot](https://i.imgur.com/vphvLgU.png)

### Additional infos
| Q                | A
| ---------------- | ---
| LUYA Version     |  1.5
| CMS | 3.3.2
| PHP Version      | 7.4
| Platform         | Apache online / WAMP locally
| Operating system | Linux / Windows

**Comment by nadar** [comment]
![image](https://user-images.githubusercontent.com/3417221/87642904-756ff400-c74a-11ea-819f-1d7efd93c368.png)

**Comment by nadar** [comment]
In the demo application its available. coud you check the console log? or inspect the html? what version of admin module?

**Comment by JohnnyMcWeed** [comment]
It's admin V. 3.3.2; no error in console log.
[This is the html](https://i.imgur.com/GcVBWvU.png)
