### ISSUE TITLE
Page copy / delete (URL path segment should contain at most 80 chars)

### ISSUE THREAD

**Issue by JohnnyMcWeed** [luyadev/luya-module-cms#279]
### What steps will reproduce the problem?
I came accross the error with another older page, where I had a copy of a page which I wanted to delete. The error was `URL path segment should contain at most 80 chars`. For deletion this check shouldn't be done at all I think.

What I just found out due to a check after this is that a page with a path of exactly 80 chars cannot be copied.

### What is the expected result?
- Possibility to copy, even if a page slug has exactly 80 chars.
- Page delete should not have checked chars (as it could be from an older page which has more. But I think this doesn't really matter, as anyone can quickly change it and delete then.)

### What do you get instead?
`URL path segment should contain at most 80 chars.`

### Additional infos
| Q                | A
| ---------------- | ---
| LUYA Version | 1.5.0
| LUYA Admin | 3.3.2
| LUYA CMS | 3.3.3
| PHP Version | 7.4

**Comment by nadar** [comment]
The max length is defined in the database, we could change that with a migration update
