### ISSUE TITLE
Redirection page doesn't respect target setting

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-cms#325]
When setting up a page as a redirection and choosing "New window" ("_blank") as a target, the link should open in a new window when clicked in the navigation. This is currently not the case, the link always opens in the same window.

**Comment by nadar** [comment]
Did you implent the target method in the link?

**Comment by nadar** [comment]
https://luya.io/api/luya-cms-menu-Item#getTarget()-detail

**Comment by nadar** [comment]
Implement for `NavTree`
