### ISSUE TITLE
CMS layout not updated correctly on import

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-cms#337]
### What steps will reproduce the problem?

Import a cms layout with the following json:

```json
{
    "rows" : [
        [
	    {"cols": 8, "var": "content", "label": "X"}
	],
        [
	    {"cols": 4, "var": "content", "label": "Y"}
	]
    ]
}
```

After the import, change the json to:

```json
{
    "rows" : [
        [
	    {"cols": 12, "var": "content", "label": "X"}
	]
    ]
}
```

and import again.  
The removed col will also be removed from the parsed JSON in the database, but the cols of the first column are still 8 instead of 12.

**Comment by rolandschaub** [comment]
I think the label isn't updated when changed, too.

**Comment by nadar** [comment]
@TheMaaarc It took my quite a while to see that you where using the same "var" name twice. Therefore this does not work. If you would have used two different var names (as designed and described https://luya.io/guide/app-cmslayouts), the import works as expected.
