### ISSUE TITLE
Configurable Preview URL

### ISSUE THREAD

**Issue by rainerCH** [luyadev/luya-module-cms#34]
Please provide a URL configuration for the "Auto-Preview" feature.
`'url' => 'http://myheadlesswebsite.com/module/?version=versionId&item=navId` (or similar)

**Comment by nadar** [comment]
We could make a module property to configure a preview url.

**Comment by nadar** [comment]
@rainerCH please try the dev-master `^1.0@dev` and let me know if this works as expected.
