### ISSUE TITLE
Possably undefined variable at NavItemPage.php

### ISSUE THREAD

**Issue by Taroxx** [luyadev/luya-module-cms#342]
Hi!

I have a proble while use a navItemPage.
There is a variable `$blockResponse` that declareted at 243 line of /vendor/luyadev/luya-module-cms/src/models/NavItemPage.php,
but if we have `$blockObject == false` this is get the error "undefined variable" on 324 line. I moved this var to "if" scope and all is ok.

**Comment by nadar** [comment]
We have triggered a new patch release
