### ISSUE TITLE
BC: New "Website" feature adds new permissions which are not set on update 

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-cms#348]
If you update to the newest version (dev-master) with the "website" feature, you will get new Permissions for the Groups and one for the Website itself. Because of these permissions, the Site tree won't be visible to anyone after updating to the latest version.

**Comment by nadar** [comment]
Thanks for the Report. Thats a very strong bc break and should be considered in a new Migration which sets all possible permissions to all groups. What do you think @boehsermoe ?

**Comment by boehsermoe** [comment]
Currently the value to allow all groups/users is 0. Maybe we could just check if there is no selected user or group (empty string) than it‘s allowed for all.
