### ISSUE TITLE
Wrong url and content format inside CMS-Module-Block

### ISSUE THREAD

**Issue by boehsermoe** [luyadev/luya-module-cms#35]
1. Problem
Inside a module thats included via cms-block the Url::to function will generate by the cms-page names (pretty url). But only when I pass an array as route it will be correctly, with a string it will generate the "raw" url (not pretty url). 

2. Problem
I include the yii CaptchaWidget inside a cms-module-block and the CaptchaAction inside a controller of this module. The CaptchaAction-Url will generate correctly because the CaptchaWidget add the "v" parameter and pass the route as array. When I call the CaptchaAction-Url I will get an empty image. The result of NavItemModule::getContent will not return direct to the output.
https://github.com/luyadev/luya-module-cms/blob/e514182e3b9f7141e1890773989af63e961df178/src/frontend/controllers/DefaultController.php#L72-L75 an array will be handled as JSON, maybe there should be inspect the`Yii::$app->response->format == Response::FORMAT_RAW` and the other formats.

**Comment by nadar** [comment]
hi @boehsermoe , first of thanks for taking time to help us improve LUYA!

1. If i understand right, its a problem with the relativ url creating? We know this (https://github.com/luyadev/luya/issues/1730) and maybe we could override Yii::$app->controller with the loaded module controller. i have to try this, not sure if it will break sth else.

2. So the captcha action set's `Response::FORMAT_RAW` - So if understand right, you suggest we should check `is_array && format == FORMAT:JSON`? Or what would you suggest?

**Comment by nadar** [comment]
@boehsermoe i just pushed a fix. 

I am not sure if we have to check for the array type and response as well. 

Please let me know if this fix your problem. You can install the dev-master by using the`^1.0@dev` constraint.

**Comment by boehsermoe** [comment]
Your fix works, thank you!
