### ISSUE TITLE
Navigation container menu disappears when creating new page

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-cms#353]
### What steps will reproduce the problem?

When adding a new page, the menu to select the navigation container disappears when selecting a placement option with the radio buttons above the menu:

![Navigationscontainer verschwindet](https://user-images.githubusercontent.com/3786245/125972061-b74edb43-1f1e-4b04-89bf-b8452a0e9d0a.gif)

dev-master version

**Comment by nadar** [comment]
The container menu should only appear when using "auf der Haupteben" - otherwise the container is provided by the parent page which is selected. This is what you mean @rolandschaub ?

**Comment by nadar** [comment]
(@boehsermoe maybe its related to the changed regarding the website selection, not sure yet)

**Comment by rolandschaub** [comment]
> The container menu should only appear when using "auf der Haupteben" - otherwise the container is provided by the parent page which is selected. This is what you mean @rolandschaub ?

Once it disappears it doesn't appear again even when "auf der Hauptebene" is selected. This can be seen in my Gif.
