### ISSUE TITLE
Misleading use of the note_add icon

### ISSUE THREAD

**Issue by hbugdoll** [luyadev/luya-module-cms#362]
**Introduction:** The `note_add` icon (page icon with a plus symbol) is used at several places in the LUYA ecosystem.
But it should only be used on the *Create new page* button in the CMS module, in the same way `create_new_folder` icon is used for the *Add folder* button.

It is used in the admin/main menu since the very beginning of LUYA,
but new users seeing this icon would think the menu item leads to a new page instead of all pages, if the menu is collapsed.

(For replacing the `note_add` icon in the Admin module another issue was opened: https://github.com/luyadev/luya-module-admin/issues/668)

---

The following changes are suggested:

**1.)** Icon @ Admin/main menu:
`note_add` --> `description` (= representing a page; a multiple pages icon isn't available)

**2.)** *Create new page* button:
`add_box` --> `note_add`

**3.)** CMS dashboard (`CmsDashboard`; like suggested for other dashboards in https://github.com/luyadev/luya-module-admin/issues/668):
`note_add` --> `add_box`

![current state](https://user-images.githubusercontent.com/6715827/135643009-5ae2ee73-7656-43c5-b1f6-9a9e67a9b5f6.png)

⬇️ 

![suggestions](https://user-images.githubusercontent.com/6715827/135643025-92e39a72-dd2c-4b0e-9bf9-29a69223b07e.png)

---

@nadar If you agree to this, I would make a PR.

**Comment by nadar** [comment]
Sounds good to me :+1:

**Comment by nadar** [comment]
@Antikon @boehsermoe opinions?

**Comment by Antikon** [comment]
I agree

**Comment by hbugdoll** [comment]
@nadar @Antikon Thanks for your positive feedback!
