### ISSUE TITLE
Missing translation in Last Updates dashboard

### ISSUE THREAD

**Issue by hbugdoll** [luyadev/luya-module-cms#369]
### What steps will reproduce the problem?

Go to admin dashboard.
In the *Last Updates* dashboard (`admin/api-cms-navitem/last-updates`) usernames are preceded by the word "by".

### What is the expected result?

"by" is translated in regard of selected language.

### What do you get instead?

"by" is not translated, because it is hardcoded in the template stored in class member `$dashboardObjects`.
(*by* means *would* in Russian, *village* in Swedish or *city* in Norwegian.)

https://github.com/luyadev/luya-module-cms/blob/53f87fb87c73039f405a0b9e9e8ae5174474ca1d/src/admin/Module.php#L79

### Questions

- How i18n can be implemented in the dashboard item template?
- Can the word "by" be omitted?

**Comment by nadar** [comment]
You can also temporary add `: "dev-master as 4.2.0"` and run composer update, i will then rewrite that dependency before release.
