### ISSUE TITLE
Wrong website_id while create NavContainer

### ISSUE THREAD

**Issue by chemezov** [luyadev/luya-module-cms#388]
### What steps will reproduce the problem?

Try to create NavContainer with non-default website in admin panel. Website field will be ignored, and NavContainer will be created with default website. Editing doesn't help either. The website remains the same.

### What do you get instead? (A Screenshot can help us a lot!)

Default website in any way.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | 4.4.0
| PHP Version      | 7.4
| Platform         | Apache (OpenServer)
| Operating system | Windows

**Comment by nadar** [comment]
i am not sure i understood correctly. You like to create a new container (NavContainer) which should not be assigned to a website? Do you have a multi website setup? Maybe a screenshot can help. Thanks for the report

**Comment by chemezov** [comment]
Sorry for misleading, there are steps to introduce:

1) I would like to create new NavContainer:

![image](https://user-images.githubusercontent.com/2368902/201014785-07148803-21e8-4f3f-b0c0-79ff373cba2f.png)

2) After saving, i get the wrong website_id in my new container:

![image](https://user-images.githubusercontent.com/2368902/201015083-4beca52e-6f87-49de-9019-d7d7af8165cc.png)

3) Event editing this record (throught admin panel), doesn't give expected result, website still has value of default website.

**Comment by nadar** [comment]
@chemezov sorry for taking so long, but should be fixed now. thanks for the report
