### ISSUE TITLE
Disallow trailing slashes in url

### ISSUE THREAD

**Issue by nadar** [luyadev/luya-module-cms#39]
Now the cms url's are valid with trailing slash, but the cms url generator never returns urls with urlManger suffix. Therefore URLs with trailing slashes are invalid urls and 404 should be thrown.

**Comment by rolandschaub** [comment]
I don't think it should throw an error but redirect to the same URL without trailing slash (permanent redirection).

**Comment by nadar** [comment]
@rolandschaub you are right, but lets make another issue for this.
