### ISSUE TITLE
Pages with same alias

### ISSUE THREAD

**Issue by hbugdoll** [luyadev/luya-module-cms#409]
### What steps will reproduce the problem?

1. Creat a page.
2. Create another page with the same `alias` (= *"URL Path segment"*) from 1.

### What is the expected result?

- An error like `nav_item_model_error_urlsegementexistsalready` is raised.

### What do you get instead? (A Screenshot can help us a lot!)

- Two pages with same `alias`, see in `cms_nav_item`:

```
+----+--------+---------+---------------+------------------+--------+--------+
| id | nav_id | lang_id | nav_item_type | nav_item_type_id | title  | alias  |
+----+--------+---------+---------------+------------------+--------+--------+
| 24 |     24 |       1 |             1 |               24 | A Page | a-page |
| 25 |     25 |       1 |             1 |               25 | A Page | a-page |
+----+--------+---------+---------------+------------------+--------+--------+

```

- So `Nav::moveToBefore()` resp. `Nav::moveToAfter()` are failing when pages with same `alias` are invoked.

- It seems that `NavItem::validateAlias()` isn't called before page creation.

### Additional infos

| Q                | A
| ---------------- | ---
| LUYA Version     | Admin 5.0, CMS 5.0
| PHP Version      | 8.2
| Platform         | Apache
| Operating system | Linux Server

**Comment by nadar** [comment]
The validation is called, but it looks like the exists query is not correctly https://github.com/luyadev/luya-module-cms/blob/master/src/models/NavItem.php#L263-L269 i will check this quickly

**Comment by hbugdoll** [comment]
@nadar First of all thank, many thanks for your quick support!

**Comment by hbugdoll** [comment]
Now we have the following situation:

Same alias is prevented
1. with same parent item
2. or at root level ("same" `parent_nav_id` = `0`).

---
But there is no support of multiple websites here. The GROUP BY clause `->groupBy('cms_nav_container.website_id')` doen't reach it. In my opinion it can be omitted because of the presence of `->exists()`.

Currently, it's not possible to have two pages with same alias but in different websites, e.g. `alias` = `'homepage'`.

The WHERE clause should be something like
`->where(['cms_nav_item.alias' => $alias, 'cms_nav_item.lang_id' => $langId, 'cms_nav.parent_nav_id' => $parentNavId, 'cms_nav_container.website_id' => $websiteId])` and `$websiteId` must be provided.
