### ISSUE TITLE
CMS: Blockvariation option doesn´t seem to work

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya-module-cms#43]
Setting the block variations inside your configs following the docs doesn´t work properly.

- it shows up in the Admin UI
- but don't have an effect on the frontend

```php
            'blockVariations' => [
                    \luya\bootstrap4\blocks\ImageBlock::variations()
                        ->add('float-right', 'Right align')->cfgs(['imgClass' => 'blockvars-img-right'])
                        ->add('float-left', 'Left align')->cfgs(['imgClass' => 'blockvars-img-right'])
                        ->add('accordion', 'Accordion Image')->cfgs(['imgClass' => 'blockvars-img-accordion'])->register(),
                    \luya\generic\blocks\TextBlock::variations()
                        ->add('bold', 'Bold Font with Markdown')->cfgs(['cssClass' => 'bold-font-class'])->vars(['textType' => 1])
                        ->add('italic', 'Italic Font')->cfgs(['cssClass' => 'italic-font-class'])->register(),
            ],
```
Do I missing something?

**Comment by nadar** [comment]
i assume those are not cfgs.

**Comment by dev7ch** [comment]
ok, i tried `cssClass`before in the image

**Comment by nadar** [comment]
you can check the config inside the block where your variations are depending on.

**Comment by dev7ch** [comment]
yes, I figured out it's only partially and limited supported, the text example didn´t workout  luckily it´s quite easy and fast to create a new block

**Comment by nadar** [comment]
@dev7ch i think the problem was you where using cfgs in stead of vars .. as you want to declare vars not cfgs, but just guessing.
