### ISSUE TITLE
Make luya\cms\Menu throw 404 instead of adding _currentAppendix

### ISSUE THREAD

**Issue by pivans** [luyadev/luya-module-cms#51]
On a request like "/demo-content/disjo" I suppose to get 404, instead of "demo-content" page.
[https://demo.luya.io/en/demo-content/disjo](https://demo.luya.io/en/demo-content/disjo)
How can I configure this?

**Comment by nadar** [comment]
Hi @pivans thanks for the report, seems to be a bug. Of course it should throw a 404.

**Comment by nadar** [comment]
I just did a little research on this issue. The "problem" is that you may have a module on this page, which can have urls. So i could make an option to configure "strict parsing".

**Comment by Robot72** [comment]
> Where should this option appear? Its a config in cms module? For example:
> 
> ```
> 'cms' => [
>     'class' => 'luya\cms\frontend\Module',
>     'strictUrlParsing' => true,
> ]
> ```

Yes, that would be nice.

**Comment by nadar** [comment]
I was just thinking about this again, maybe its bad to configure this in configs, maybe a block should have an flag which can be triggered if NOT strict url parsing is required, for example the module block would implement:

```php
public function requireUrlWildcard()
{
   return true;
}
```

(all other block which does not need this kind of wildcard urls would return false)

If this is the case (return true), the strict url parsing is automatically disabled for this page.

**Comment by Robot72** [comment]
> requireUrlWildcard

That is, using the requireUrlWildcard method it will be possible to override more flexibly: not only for the luya\cms\frontend\Module, but also for other modules? Do I understand correctly?

**Comment by nadar** [comment]
I was more thinking about blocks. Because the module block is the only situation where "url wildcard" behavior is required.

**Comment by Robot72** [comment]
@nadar do you talk about [the cms block](https://luya.io/guide/app-blocks) ? Or do you talk about a module class (http://i.prntscr.com/ViSlIWLyTUmkebHvbl9ntg.png) ?

**Comment by nadar** [comment]
Yes CMS Blocks. Because CMS Blocks are the only situation which need url wildcards but only when the luya cms module block integrates modules.https://github.com/luyadev/luya-module-cms/blob/master/src/frontend/blocks/ModuleBlock.php

**Comment by Robot72** [comment]
I think it will be good. I would like to try this solution.

**Comment by nadar** [comment]
This is also a problem for cms redirects - in order to make a redirect from an existing subpage node this is not possible. example:

/de/foobar <= this page exists
/de/foobar/john-doe <= this page does not exists

now its not possible to make a redirect trough redirects table from `de/foobar/john-doe` as the cms says: if have found an item - instead of a 404 - which will then activate the cms redirect table.

**Comment by nadar** [comment]
URL Wildcard paths are now only valid if the parent page is a module or strict parsing is disabled. 

Therfore this is a breaking change. When a page contains the **module block** (not a page which is a module) and the module block can create and follow urls the strict parsing option must disabled in the nav item setting panel.

![image](https://user-images.githubusercontent.com/3417221/53495276-e48a7100-3a9f-11e9-8f04-e005bf969b7d.png)
