### ISSUE TITLE
Feature Request: Schedule visibility of block

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-cms#53]
It would be great to be able to schedule the visibility of a content block (making this a core feature of all blocks). A clock button could open a tab with the following form fields:

[x] Only display this block during the following timeframe:
From: [dd].[mm].[yyyy]  [hh]:[ii]
To: [dd].[mm].[yyyy]  [hh]:[ii]

Leave start date empty to only schedule end date.
Leave end date empty to only schedule start date.

**Comment by nadar** [comment]
Good idea. Tagged as 1.1.0 as it requires a migration.

**Comment by nadar** [comment]
i close this issue due to a generic scheduler see: https://github.com/luyadev/luya-module-cms/issues/53
