### ISSUE TITLE
Feature Request: Make permission for the luya-cms-toolbar

### ISSUE THREAD

**Issue by nick-denry** [luyadev/luya-module-cms#59]
I think it is good to provide a permission or option to enable/disable luya-cms-toolbar.

The reason is that toolbar colud be overhead/annoyiing for some particular group of admin users (e.g. sellers), cause they know nothing about content managment or seo.

For my opion a permission is better than an option.

**Comment by nadar** [comment]
@nick-denry sure, will add a module property you can override/disable in the config.

**Comment by nadar** [comment]
https://luya.io/api/luya-cms-frontend-Module#$overlayToolbar-detail
