### ISSUE TITLE
Url::toMenuItem alternative for nav_id

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-cms#61]
Create an alternative function to generate a link to a menuItem by navId. Url::toMenuItem searches by the actual id that is only visible in the database.

**Comment by nadar** [comment]
Agree, lets add: `luya\cms\helpers\Url::toMenu($navId, [])`

**Comment by nadar** [comment]
Mabye also consider rename `toMenu` with `toNav` also for `toMenuItem` as `toNavItem`.
