### ISSUE TITLE
Menu should respect 'sort_index' attribute of any items

### ISSUE THREAD

**Issue by nick-denry** [luyadev/luya-module-cms#62]
Hi!

Menu doesn't respect 'sort_index' property of InjectedItem if different elements are used.

I have a menu with 2 cms pages items, and want to inject another item from module.

Do it via subclassing  `luya\cms\menu\InjectItem`. There is `toArray()` method of my custon InjectItem class

```php
<?php

namespace app\modules\mymodule\menu;

use Yii;
use luya\cms\menu\InjectItem as BaseInjectItem;

class InjectItem extends BaseInjectItem
{

    /**
     * Parse the injected item to an array.
     *
     * @return array
     */
    public function toArray()
    {
        return [
            'id' => '43',
            'nav_id' => '2',
            'lang' => 'ru',
            'link' => '/mymodule/somelink',
            'title' => 'Injected Item',
            'alias' => 'somelink',
            'description' => '',
            'keywords' => NULL,
            'create_user_id' => '1',
            'update_user_id' => '1',
            'timestamp_create' => '1457091369',
            'timestamp_update' => '1483367249',
            'is_home' => '0',
            'parent_nav_id' => '0',
            'sort_index' => '0',
            'is_hidden' => '0',
            'type' => '1',
            'nav_item_type_id' => '42',
            'redirect' => false,
            'module_name' => false,
            'container' => 'mycontainer',
            'depth' => 1,
        ];
    }
}
```

Then I've got this:

![2018-04-09 23 19 34](https://user-images.githubusercontent.com/1450983/38520818-88ec8d08-3c4c-11e8-9648-48e94ee4a1e2.png)

The first two items are pages. Items have following `sort_index` values:

```
["sort_index"]=> string(1) "1" first
["sort_index"]=> string(1) "2" second
["sort_index"]=> string(1) "0" injected
```

But injected item appears last.

**Comment by hbugdoll** [comment]
> The first two items are pages. Items have following `sort_index` values:
> 
> ```
> ["sort_index"]=> string(1) "1" first
> ["sort_index"]=> string(1) "2" second
> ["sort_index"]=> string(1) "0" injected
> ```
> 
> But injected item appears last.

This behavior depends highly on how you access the menu data.
Assuming they are accessed via `Yii::$app->menu->find()->all()` then `sort_index` is not taken into account.
One have to sort explicitly: `Yii::$app->menu->find()->orderBy(['sort_index' => SORT_ASC])->all()`.

Here is a screenshot of my test output using your subclass:
![Screenshot](https://github.com/luyadev/luya-module-cms/assets/6715827/5e8e461a-15ba-4f72-a032-60e488a2423e)

@nadar In my opinion this issue can be closed.

**Comment by nadar** [comment]
maybe we could add something to the docs? That would be great!

https://luya.io/guide/cms/menu.html#menu-item-injection

**Comment by hbugdoll** [comment]
@nadar Thanks for merging https://github.com/luyadev/luya.io/pull/81. This issue can be closed now.
