### ISSUE TITLE
Deleting a CMS block does not close confirm dialog

### ISSUE THREAD

**Issue by cebe** [luyadev/luya-module-cms#66]
When deleting a block in CMS, the confirm dialog does not close when clicking "Yes":

![bildschirmfoto von 2018-05-07 12-19-22](https://user-images.githubusercontent.com/189796/39697404-1e1eefd8-51f1-11e8-821c-da1f96de3437.png)

Clicking Yes multiple times results in the error:

![bildschirmfoto von 2018-05-07 12-21-34](https://user-images.githubusercontent.com/189796/39697435-360382f8-51f1-11e8-8f40-c59697245c3e.png)

the deletion itself works as the change is visible in the background. also closing the dialog via "Cancel" works.

Browser: Firefox 59.0.2 (64-Bit)

**Comment by nadar** [comment]
Thanks. Looks like a bug from angular strict di changes, will fix asap.
