### ISSUE TITLE
File download Content-Type is application/octet-stream

### ISSUE THREAD

**Issue by cebe** [luyadev/luya-module-cms#85]
I uploaded a PDF file for download. Linking to that file presents the dowload as `Content-Type: application/octet-stream` which causes the browser to be unable to show it as PDF and will only save the download. Ideally serving the file with the correct content type would allow directly opening it as PDF.

Given that `Type: pdf` is already shown in the admin backend I assume the information is already available for serving the correct mime type.

**Comment by nadar** [comment]
So the mime type would have been correctly stored in the admin_file table? 

This is where we provide the file download: https://github.com/luyadev/luya-module-admin/blob/master/src/controllers/FileController.php#L46

Maybe providing the `mimeType` from the database table would fix the problem?

**Comment by cebe** [comment]
yes, that fixes it. Thanks for the hint. See https://github.com/luyadev/luya-module-admin/pull/149 for a fix.
While I was at that file already, I also fixed a race condition in the download counter update.
