### ISSUE TITLE
Block variation "default"

### ISSUE THREAD

**Issue by TheMaaarc** [luyadev/luya-module-cms#86]
It would be nice to have the possibility to change the blocks default values through a "default" variation.

Maybe something like this would work?

```php
TextBlock::variations()
    ->add('default')->vars(['textType' => 1])
    ->register()
```

Technically it would still be a "variation" even tho it's the default one that can't be chosen by the user.

Use cases:
Title block: Limit the type dropdown to only h1 and h2, add default css class
Text block: Enable markdown by default, add default css class
...

**Comment by nadar** [comment]
I agree with this missing function, sometimes it would be very useful to apply a default class for images.  The approach you provided looks almost good to me. Maybe using something like this:

```php
TextBlock::variations()->default()->vars(['textType' => 1])->register()
```

Is now `default()` would be available in your IDE while typing.

**Comment by nadar** [comment]
rename `default` to `asDefault()`

> PHP Parse error:  syntax error, unexpected 'default' (T_DEFAULT), expecting  
   identifier (T_STRING)
